import { OrchestratorEvent, OrchestratorEventType, OrchestratorEventSeverity } from '../types';

export const INITIAL_ORCHESTRATOR_EVENTS: OrchestratorEvent[] = [
  {
    id: 'evt-101',
    timestamp: '11:42:01.120',
    isoTime: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    taskId: 'task-sourcing-8819',
    taskName: '1688 Factory Sourcing & Landed Cost Pipeline',
    stepNumber: 1,
    totalSteps: 5,
    type: 'TASK_INITIATED',
    severity: 'info',
    sourceModule: 'Orchestrator Core',
    title: 'Инициализация пайплайна закупки 1688 (SKU: 1688-GZ-88190)',
    details: 'Получен сигнал на пересчет себестоимости и DDP-логистики партии шелковых платьев (200 шт, Гуанчжоу).',
    executionMs: 14,
    payload: {
      sku: '1688-GZ-88190',
      factoryCity: 'Guangzhou',
      targetQty: 200,
      currency: 'CNY',
      warehouseDestination: 'Koledino_WB',
    },
  },
  {
    id: 'evt-102',
    timestamp: '11:42:01.340',
    isoTime: new Date(Date.now() - 1000 * 60 * 12 + 220).toISOString(),
    taskId: 'task-sourcing-8819',
    taskName: '1688 Factory Sourcing & Landed Cost Pipeline',
    stepNumber: 2,
    totalSteps: 5,
    type: 'CONNECTOR_DISPATCH',
    severity: 'info',
    sourceModule: '1688 Connector',
    title: 'Запрос к 1688 Open API: alibaba.crossborder.product.priceTier.get',
    details: 'Синхронизация актуальных ступеней оптовых цен (¥42 при партии >=200 шт) и статуса верификации фабрики.',
    executionMs: 220,
    payload: {
      endpoint: 'https://gw.open.1688.com/openapi/param2/1/aliexpress.open/api.getLandedCost/741',
      httpStatus: 200,
      factoryVerified: true,
      unitPriceCny: 42.0,
      moqMet: true,
    },
  },
  {
    id: 'evt-103',
    timestamp: '11:42:01.590',
    isoTime: new Date(Date.now() - 1000 * 60 * 12 + 470).toISOString(),
    taskId: 'task-sourcing-8819',
    taskName: '1688 Factory Sourcing & Landed Cost Pipeline',
    stepNumber: 3,
    totalSteps: 5,
    type: 'CALCULATION_STEP',
    severity: 'decision',
    sourceModule: 'SCM & Logistics',
    title: 'Калькуляция DDP себестоимости: Фабрика → Карго Авто → Белая растаможка',
    details: 'Себестоимость единицы: ¥42 * 13.45 ₽ = 564.9 ₽ + Логистика $3.8/кг (160 ₽) + Таможня/Маркировка «Честный Знак» (95.1 ₽) = 820 ₽/ед.',
    executionMs: 35,
    payload: {
      factoryCostRub: 564.9,
      freightCostRub: 160.0,
      customsAndLabelingRub: 95.1,
      totalLandedCostRub: 820.0,
      cnyRate: 13.45,
      deliveryEtaDays: 14,
    },
    decisionPath: {
      confidenceScore: 0.98,
      marginBefore: 38.4,
      marginAfter: 54.2,
      safetyChecks: ['MOQ_VERIFIED', 'CERTIFICATE_EAC_MATCH', 'CHESTNY_ZNAK_READY'],
    },
  },
  {
    id: 'evt-104',
    timestamp: '11:42:01.710',
    isoTime: new Date(Date.now() - 1000 * 60 * 12 + 590).toISOString(),
    taskId: 'task-sourcing-8819',
    taskName: '1688 Factory Sourcing & Landed Cost Pipeline',
    stepNumber: 4,
    totalSteps: 5,
    type: 'GUARDRAIL_CHECK',
    severity: 'success',
    sourceModule: 'Safety Guardrails',
    title: 'Проверка Safety Guardrails & Margin Floor (Правило #R-04)',
    details: 'Ожидаемая маржинальность розницы WB (2 450 ₽) составляет 54.2%, что превышает минимальный порог безопасности 25.0%.',
    executionMs: 18,
    decisionPath: {
      ruleId: 'rule-margin-guard',
      ruleName: 'Margin Floor Guardrail >= 25%',
      conditionPassed: true,
      confidenceScore: 1.0,
      safetyChecks: ['PRICE_COLLUSION_CHECK_PASSED', 'MARGIN_FLOOR_PASSED'],
    },
  },
  {
    id: 'evt-105',
    timestamp: '11:42:01.890',
    isoTime: new Date(Date.now() - 1000 * 60 * 12 + 770).toISOString(),
    taskId: 'task-sourcing-8819',
    taskName: '1688 Factory Sourcing & Landed Cost Pipeline',
    stepNumber: 5,
    totalSteps: 5,
    type: 'TASK_COMPLETED',
    severity: 'success',
    sourceModule: 'Orchestrator Core',
    title: 'Завершение задачи: PO-черновик контракта сформирован',
    details: 'Сформирован инвойс на партию 200 шт (¥8 400). Рекомендация добавлена в AI Assistant и Safe Action Audit Log.',
    executionMs: 25,
    payload: {
      poNumber: 'PO-2026-CN-88190',
      totalOrderCny: 8400,
      totalOrderRub: 112980,
      auditLogId: 'audit-sourcing-8819',
    },
  },

  {
    id: 'evt-106',
    timestamp: '11:44:10.050',
    isoTime: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
    taskId: 'task-repricing-prod7',
    taskName: 'Emergency Repricing & BuyBox Protection',
    stepNumber: 1,
    totalSteps: 4,
    type: 'ANOMALY_DETECTED',
    severity: 'warning',
    sourceModule: 'Decision Brain',
    title: 'Обнаружен демпинг конкурента NordBag Casual (SKU: WB-77291048)',
    details: 'Конкурент снизил цену с 2 190 ₽ до 1 950 ₽ (-240 ₽). Органическая позиция товара №7 упала с 1-го до 4-го места.',
    executionMs: 42,
    payload: {
      sku: 'WB-77291048',
      previousRank: 1,
      currentRank: 4,
      competitorPrice: 1950,
      currentOurPrice: 2190,
      stockKoledino: 12,
    },
  },
  {
    id: 'evt-107',
    timestamp: '11:44:10.310',
    isoTime: new Date(Date.now() - 1000 * 60 * 9 + 260).toISOString(),
    taskId: 'task-repricing-prod7',
    taskName: 'Emergency Repricing & BuyBox Protection',
    stepNumber: 2,
    totalSteps: 4,
    type: 'RULES_EVALUATED',
    severity: 'decision',
    sourceModule: 'Rule Engine',
    title: 'Срабатывание детерминированного бизнес-правила #R-02 (Репрайсер)',
    details: 'Правило "Если конкурент снижает цену и остаток > 10 шт -> снизить цену до MinPrice, но не ниже себестоимости + 15%".',
    executionMs: 16,
    decisionPath: {
      ruleId: 'rule-2-repricer',
      ruleName: 'Dynamic Repricer Rule (MinMargin 15%)',
      conditionPassed: true,
      confidenceScore: 1.0,
      marginBefore: 42.1,
      marginAfter: 36.8,
    },
    payload: {
      proposedPrice: 1990,
      costPrice: 790,
      calculatedMargin: 36.8,
    },
  },
  {
    id: 'evt-108',
    timestamp: '11:44:10.450',
    isoTime: new Date(Date.now() - 1000 * 60 * 9 + 400).toISOString(),
    taskId: 'task-repricing-prod7',
    taskName: 'Emergency Repricing & BuyBox Protection',
    stepNumber: 3,
    totalSteps: 4,
    type: 'ACTION_PREPARED',
    severity: 'info',
    sourceModule: 'Orchestrator Core',
    title: 'Подготовка двухуровневого действия: WRITE (Цена) + READ (Склад 1688)',
    details: 'Действие готово к валидации оператором селлера в один клик. Прямой доступ к API маркетплейса защищен.',
    executionMs: 20,
    payload: {
      actionCardType: 'price_adjust',
      targetPrice: 1990,
      factoryRestockTarget: 300,
    },
  },
  {
    id: 'evt-109',
    timestamp: '11:44:10.820',
    isoTime: new Date(Date.now() - 1000 * 60 * 9 + 770).toISOString(),
    taskId: 'task-repricing-prod7',
    taskName: 'Emergency Repricing & BuyBox Protection',
    stepNumber: 4,
    totalSteps: 4,
    type: 'TASK_COMPLETED',
    severity: 'success',
    sourceModule: 'Orchestrator Core',
    title: 'Карточка действия опубликована в ленту решений AI Assistant',
    details: 'Оркестратор перешёл в режим ожидания подтверждения оператором (Human-in-the-loop).',
    executionMs: 12,
  },

  {
    id: 'evt-110',
    timestamp: '11:46:22.010',
    isoTime: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    taskId: 'task-health-sync-ozon',
    taskName: 'Ozon Seller API v2 Daily Synchronizer',
    stepNumber: 1,
    totalSteps: 3,
    type: 'CONNECTOR_DISPATCH',
    severity: 'info',
    sourceModule: 'Ozon Connector',
    title: 'Отправка пачки запросов /v2/product/info/stocks & /v1/analytics/data',
    details: 'Синхронизация остатков Хоругвино/Казань и рекламных расходов трафаретов.',
    executionMs: 180,
  },
  {
    id: 'evt-111',
    timestamp: '11:46:22.250',
    isoTime: new Date(Date.now() - 1000 * 60 * 4 + 240).toISOString(),
    taskId: 'task-health-sync-ozon',
    taskName: 'Ozon Seller API v2 Daily Synchronizer',
    stepNumber: 2,
    totalSteps: 3,
    type: 'CRITICAL_ERROR',
    severity: 'error',
    sourceModule: 'Ozon Connector',
    title: 'HTTP 429 Too Many Requests (Rate Limit Exceeded: 100 req/min)',
    details: 'Превышен лимит параллельных запросов Ozon Open API. Сработал предохранитель Circuit Breaker.',
    executionMs: 65,
    payload: {
      httpCode: 429,
      retryAfterSeconds: 3,
      circuitBreakerState: 'HALF_OPEN',
    },
    errorStack: 'OzonApiRateLimitError: Rate limit quota exhausted on endpoint /v1/analytics/data\n  at OzonConnector.dispatch (connectors/ozon.ts:142)\n  at Orchestrator.executeTask (core/orchestrator.ts:89)',
  },
  {
    id: 'evt-112',
    timestamp: '11:46:25.400',
    isoTime: new Date(Date.now() - 1000 * 60 * 4 + 3390).toISOString(),
    taskId: 'task-health-sync-ozon',
    taskName: 'Ozon Seller API v2 Daily Synchronizer',
    stepNumber: 3,
    totalSteps: 3,
    type: 'RETRY_ATTEMPT',
    severity: 'success',
    sourceModule: 'Safety Guardrails',
    title: 'Автоматический Retry с Exponential Backoff (3.1s) — Успех 200 OK',
    details: 'Повторный вызов успешно завершён. Получены метрики по 6 SKU магазина SmartLiving RU.',
    executionMs: 140,
    payload: {
      httpCode: 200,
      retriesDone: 1,
      circuitBreakerState: 'CLOSED_NORMAL',
      productsSynced: 6,
    },
  },
];

export interface ScenarioTemplate {
  id: string;
  name: string;
  badge: string;
  description: string;
  iconName: string;
  eventsCount: number;
  durationSec: number;
}

export const SCENARIO_TEMPLATES: ScenarioTemplate[] = [
  {
    id: 'sc-1688-sourcing',
    name: '🇨🇳 Полный цикл 1688 Sourcing → DDP Карго → Wildberries FBO',
    badge: 'Supply Chain & Sourcing',
    description: 'Оркестрация поиска фабрики в Гуанчжоу, проверка MOQ, расчет белой таможни и выгрузка лота на склад Коледино.',
    iconName: 'Factory',
    eventsCount: 5,
    durationSec: 4,
  },
  {
    id: 'sc-repricer-emergency',
    name: '⚡ Экстренный репрайсер и защита маржинальности при демпинге',
    badge: 'Pricing & Risk Guard',
    description: 'Детекция демпинга конкурента, проверка порога Margin Floor (>=20%), подготовка безопасного изменения цены.',
    iconName: 'Zap',
    eventsCount: 4,
    durationSec: 3,
  },
  {
    id: 'sc-api-failover',
    name: '🚨 Симуляция сбоя API Маркетплейса (429 Rate Limit & Circuit Breaker)',
    badge: 'Fault Tolerance & Self-Healing',
    description: 'Обработка отказа шлюза маркетплейса, изоляция очереди задач, экспоненциальная задержка и восстановление.',
    iconName: 'ShieldAlert',
    eventsCount: 4,
    durationSec: 3.5,
  },
  {
    id: 'sc-ai-diagnosis',
    name: '🧠 AI Deep Diagnostics: Расследование просадки позиций и DRR',
    badge: 'Decision Intelligence',
    description: 'Анализ 4 факторов падения конверсии (индексация ключей, складской остаток, отзывы, биддинг рекламы).',
    iconName: 'Brain',
    eventsCount: 5,
    durationSec: 4,
  },
];

export function generateSimulatedScenarioEvents(scenarioId: string): OrchestratorEvent[] {
  const now = new Date();
  const baseTimeStr = () => {
    const d = new Date();
    return `${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}:${d.getSeconds().toString().padStart(2, '0')}.${Math.floor(Math.random() * 900 + 100)}`;
  };

  const randomTaskId = `task-${Math.random().toString(36).substring(2, 7)}`;

  if (scenarioId === 'sc-1688-sourcing') {
    return [
      {
        id: `evt-${Date.now()}-1`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: '1688 Factory Sourcing & Cross-Border Logistics',
        stepNumber: 1,
        totalSteps: 5,
        type: 'TASK_INITIATED',
        severity: 'info',
        sourceModule: 'Orchestrator Core',
        title: 'Запуск задачи подбора фабричного лота 1688 (Термобутылки / Иу)',
        details: 'Анализ фабрик в Чжэцзяне / Иу с минимальным MOQ от 100 шт и верификацией Gold Supplier.',
        executionMs: 15,
        payload: {
          category: 'Kitchen & Thermal Ware',
          targetMoq: 100,
          region: 'Zhejiang_Yiwu',
        },
      },
      {
        id: `evt-${Date.now()}-2`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: '1688 Factory Sourcing & Cross-Border Logistics',
        stepNumber: 2,
        totalSteps: 5,
        type: 'CONNECTOR_DISPATCH',
        severity: 'info',
        sourceModule: '1688 Connector',
        title: 'Запрос цен фабрик 1688: Taobao/Alibaba Cross-border API',
        details: 'Найдено 3 верифицированных поставщика. Лучшая фабричная ставка: ¥24.5 / ед ($3.42) при заказе 300 шт.',
        executionMs: 210,
        payload: {
          supplierWeChat: 'yiwu_apex_bag',
          quoteCny: 24.5,
          ratingScore: 4.94,
        },
      },
      {
        id: `evt-${Date.now()}-3`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: '1688 Factory Sourcing & Cross-Border Logistics',
        stepNumber: 3,
        totalSteps: 5,
        type: 'CALCULATION_STEP',
        severity: 'decision',
        sourceModule: 'SCM & Logistics',
        title: 'Расчет DDP себестоимости под ключ (Юань ¥ → Рубль ₽)',
        details: 'Себестоимость лота: ¥24.5 * 13.45 = 329.5 ₽ + Карго 110 ₽ + Сертификация 45 ₽ = 484.5 ₽. Маржинальность в РФ (1 390 ₽) = 65.1%.',
        executionMs: 28,
        decisionPath: {
          confidenceScore: 0.99,
          marginBefore: 34.1,
          marginAfter: 65.1,
          safetyChecks: ['DIRECT_FACTORY_PASSED', 'DDP_LOGISTICS_LOCKED'],
        },
      },
      {
        id: `evt-${Date.now()}-4`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: '1688 Factory Sourcing & Cross-Border Logistics',
        stepNumber: 4,
        totalSteps: 5,
        type: 'GUARDRAIL_CHECK',
        severity: 'success',
        sourceModule: 'Safety Guardrails',
        title: 'Валидация бизнес-правил: Margin Floor & Lead Time Check',
        details: 'Срок доставки 12-16 дней укладывается в норматив склада Коледино до окончания остатков (хватит на 21 день).',
        executionMs: 14,
      },
      {
        id: `evt-${Date.now()}-5`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: '1688 Factory Sourcing & Cross-Border Logistics',
        stepNumber: 5,
        totalSteps: 5,
        type: 'TASK_COMPLETED',
        severity: 'success',
        sourceModule: 'Orchestrator Core',
        title: 'План закупки 1688 успешно сформирован и передан в Safe Audit Log',
        details: 'Создан проект контракта PO-CN-YIWU-7729. Уведомление направлено в Telegram селлера.',
        executionMs: 22,
        payload: {
          poId: 'PO-CN-YIWU-7729',
          totalUnits: 300,
          totalAmountRub: 145350,
        },
      },
    ];
  }

  if (scenarioId === 'sc-repricer-emergency') {
    return [
      {
        id: `evt-${Date.now()}-1`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Dynamic Pricing & Margin Floor Protection',
        stepNumber: 1,
        totalSteps: 4,
        type: 'ANOMALY_DETECTED',
        severity: 'warning',
        sourceModule: 'Decision Brain',
        title: 'Сканирование конкурентов: Зафиксирован демпинг на Wildberries',
        details: 'Конкурент снизил цену на аналогичный товар до 1 890 ₽. Наш текущий прайс: 2 190 ₽.',
        executionMs: 38,
      },
      {
        id: `evt-${Date.now()}-2`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Dynamic Pricing & Margin Floor Protection',
        stepNumber: 2,
        totalSteps: 4,
        type: 'RULES_EVALUATED',
        severity: 'decision',
        sourceModule: 'Rule Engine',
        title: 'Оценка правила #R-02 (Динамический репрайсинг WB/Ozon)',
        details: 'Рассчитана оптимальная цена: 1 950 ₽. Прибыль с единицы составит 810 ₽ (маржа 41.5% > 20% порога).',
        executionMs: 19,
        decisionPath: {
          ruleId: 'rule-repricer-auto',
          ruleName: 'Dynamic Repricer Rule',
          conditionPassed: true,
          marginBefore: 49.0,
          marginAfter: 41.5,
        },
      },
      {
        id: `evt-${Date.now()}-3`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Dynamic Pricing & Margin Floor Protection',
        stepNumber: 3,
        totalSteps: 4,
        type: 'GUARDRAIL_CHECK',
        severity: 'success',
        sourceModule: 'Safety Guardrails',
        title: 'Safety Guardrail: Лимит разового изменения цены <= 15%',
        details: 'Коррекция цены составляет -10.9% (в пределах разрешенного коридора безопасности).',
        executionMs: 12,
      },
      {
        id: `evt-${Date.now()}-4`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Dynamic Pricing & Margin Floor Protection',
        stepNumber: 4,
        totalSteps: 4,
        type: 'ACTION_COMMITTED',
        severity: 'success',
        sourceModule: 'Orchestrator Core',
        title: 'Новая цена 1 950 ₽ подготовлена и записана в журнал аудита',
        details: 'Оркестратор сгенерировал интерактивную карточку действия для селлера.',
        executionMs: 25,
      },
    ];
  }

  if (scenarioId === 'sc-api-failover') {
    return [
      {
        id: `evt-${Date.now()}-1`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Marketplace Gateway Sync & Fault Tolerance',
        stepNumber: 1,
        totalSteps: 4,
        type: 'CONNECTOR_DISPATCH',
        severity: 'info',
        sourceModule: 'WB API v3',
        title: 'Массовый опрос эндпоинта /api/v3/orders/status',
        details: 'Синхронизация статусов сборочных заданий FBS.',
        executionMs: 85,
      },
      {
        id: `evt-${Date.now()}-2`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Marketplace Gateway Sync & Fault Tolerance',
        stepNumber: 2,
        totalSteps: 4,
        type: 'CRITICAL_ERROR',
        severity: 'error',
        sourceModule: 'WB API v3',
        title: 'HTTP 502 Bad Gateway / Connection Timeout от шлюза Wildberries',
        details: 'Внешний API маркетплейса временно недоступен. Сработал Circuit Breaker (OPEN).',
        executionMs: 1100,
        errorStack: 'GatewayTimeoutException: wildberries-openapi-proxy timeout after 1100ms\n  at WBConnector.pollOrders (wb/client.ts:88)',
      },
      {
        id: `evt-${Date.now()}-3`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Marketplace Gateway Sync & Fault Tolerance',
        stepNumber: 3,
        totalSteps: 4,
        type: 'RETRY_ATTEMPT',
        severity: 'warning',
        sourceModule: 'Safety Guardrails',
        title: 'Circuit Breaker: Очередь задач переведена в режим Dead Letter Queue Retry',
        details: 'Автоматическая пауза 2.5s. Предотвращение каскадного падения системы селлера.',
        executionMs: 30,
      },
      {
        id: `evt-${Date.now()}-4`,
        timestamp: baseTimeStr(),
        isoTime: now.toISOString(),
        taskId: randomTaskId,
        taskName: 'Marketplace Gateway Sync & Fault Tolerance',
        stepNumber: 4,
        totalSteps: 4,
        type: 'TASK_COMPLETED',
        severity: 'success',
        sourceModule: 'Orchestrator Core',
        title: 'Шлюз восстановил работу. Повторный опрос завершён со статусом 200 OK',
        details: 'Синхронизировано 42 заказа FBS. Ни одно действие не потеряно.',
        executionMs: 95,
      },
    ];
  }

  // AI Diagnosis Scenario
  return [
    {
      id: `evt-${Date.now()}-1`,
      timestamp: baseTimeStr(),
      isoTime: now.toISOString(),
      taskId: randomTaskId,
      taskName: 'AI Multi-Factor Anomaly Diagnostics',
      stepNumber: 1,
      totalSteps: 5,
      type: 'TASK_INITIATED',
      severity: 'info',
      sourceModule: 'Orchestrator Core',
      title: 'Инициализация многофакторного анализа просадки SKU: WB-18492019',
      details: 'Запуск 4 параллельных диагностических анализаторов: Price, SEO, Stock, Feedback.',
      executionMs: 12,
    },
    {
      id: `evt-${Date.now()}-2`,
      timestamp: baseTimeStr(),
      isoTime: now.toISOString(),
      taskId: randomTaskId,
      taskName: 'AI Multi-Factor Anomaly Diagnostics',
      stepNumber: 2,
      totalSteps: 5,
      type: 'LLM_REASONING_STEP',
      severity: 'decision',
      sourceModule: 'Decision Brain',
      title: 'Семантический аудит отзывов: Кластеризация негатива по упаковке',
      details: 'Кластер "Помятая коробка" (12.4% жалоб) снизил средний балл с 4.95 до 4.88, ухудшив конверсию карточки на -3.2%.',
      executionMs: 180,
    },
    {
      id: `evt-${Date.now()}-3`,
      timestamp: baseTimeStr(),
      isoTime: now.toISOString(),
      taskId: randomTaskId,
      taskName: 'AI Multi-Factor Anomaly Diagnostics',
      stepNumber: 3,
      totalSteps: 5,
      type: 'CALCULATION_STEP',
      severity: 'info',
      sourceModule: 'SCM & Logistics',
      title: 'Расчет упущенной выгоды селлера: 14 200 ₽/день',
      details: 'Суммарные потери из-за снижения CR в корзину за последние 7 дней составили ~99 400 ₽.',
      executionMs: 24,
    },
    {
      id: `evt-${Date.now()}-4`,
      timestamp: baseTimeStr(),
      isoTime: now.toISOString(),
      taskId: randomTaskId,
      taskName: 'AI Multi-Factor Anomaly Diagnostics',
      stepNumber: 4,
      totalSteps: 5,
      type: 'ACTION_PREPARED',
      severity: 'decision',
      sourceModule: 'Decision Brain',
      title: 'Синтез комплексного рецепта устранения первопричины',
      details: '1) Согласовать усиленную упаковку тубуса с фабрикой в WeChat (¥1.2/ед). 2) Ответить авторам отзывов с промокодом.',
      executionMs: 120,
    },
    {
      id: `evt-${Date.now()}-5`,
      timestamp: baseTimeStr(),
      isoTime: now.toISOString(),
      taskId: randomTaskId,
      taskName: 'AI Multi-Factor Anomaly Diagnostics',
      stepNumber: 5,
      totalSteps: 5,
      type: 'TASK_COMPLETED',
      severity: 'success',
      sourceModule: 'Orchestrator Core',
      title: 'Диагностический отчёт зафиксирован и выгружен в UI селлера',
      details: 'Статус товара обновлен на ATTENTION_NEEDED. Рекомендации отправлены в утренний дайджест.',
      executionMs: 18,
    },
  ];
}
